import Foundation


var array: [IBlock] = []

array.append(Variable(id: 1, type: .int, name: "a", value: "1"))
array.append(Function(id: 2, value: "add(int a, int b)"))
array.append(BlockDelimiter(type: .begin))
array.append(Variable(id: 3, type: .int, name: "c", value: "a + b"))
array.append(Loop(id: 6, type: .forLoop, value: "i = 0; i < 10; i++"))
array.append(BlockDelimiter(type: .begin))
array.append(Variable(id: 7, type: .int, name: "e", value: "i"))
array.append(BlockDelimiter(type: .end))
array.append(Returning(id: 4, value: "c"))
array.append(BlockDelimiter(type: .end))
array.append(Variable(id: 5, type: .int, name: "d", value: "add(1, 2)"))

array.append(Variable(id: 0, type: .int, name: "b", value: "10"))
array.append(Variable(id: 1, type: .int, name: "a", value: "7 + b + 2"))
array.append(Output(id: 2, value: "a"))
array.append(Condition(id: 3, type: .ifBlock, value: "a != b"))
array.append(BlockDelimiter(type: DelimiterType.begin))
array.append(Variable(id: 4, type: .int, name: "b", value: "b + 10"))
array.append(Variable(id: 5, type: .int, name: "a", value: "a * 2"))
array.append(Output(id: 6, value: "a"))
array.append(BlockDelimiter(type: DelimiterType.end))
array.append(Condition(id: 7, type: .ifBlock,  value: "(6 + 2) % 8 == 0"))
array.append(BlockDelimiter(type: DelimiterType.begin))
array.append(Variable(id: 8, type: .int, name: "b", value: "b + 100"))
array.append(Condition(id: 9, type: .ifBlock,  value: "a != b"))
array.append(BlockDelimiter(type: DelimiterType.begin))
array.append(Variable(id: 10, type: .int, name: "b", value: "b + 100"))
array.append(Output(id: 11, value: "b"))
array.append(BlockDelimiter(type: DelimiterType.end))
array.append(BlockDelimiter(type: DelimiterType.end))
array.append(Output(id: 12, value: "b"))

let tree = Tree()
tree.setBlocks(array)
tree.buildTree()
print("hi")